# Generated by Django 3.2.1 on 2021-05-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='namee',
        ),
    ]
