# Generated by Django 3.2.1 on 2021-05-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0002_rename_name_userprofile_namee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='namee',
            new_name='name',
        ),
    ]
